-- Migración: Crear tablas para Exploradores Autónomos (monitored_sources y agent_runs)
-- Ruta: supabase/migrations/01_create_agents_tables.sql

-- Crear tabla de fuentes monitoreadas
CREATE TABLE IF NOT EXISTS monitored_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL, -- 'luma_profile', 'twitter', 'discord'
  url_or_handle text NOT NULL, -- e.g. 'https://lu.ma/chc_buenosaires' o '@ba_cripto'
  city text NOT NULL, -- 'AMBA', 'Bogotá', 'Santiago'
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  last_scanned_at timestamptz
);

-- Crear tabla de historial de ejecuciones de agentes
CREATE TABLE IF NOT EXISTS agent_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
  status text NOT NULL, -- 'running', 'success', 'failed'
  new_events_count integer DEFAULT 0,
  log_output text,
  created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE monitored_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_runs ENABLE ROW LEVEL SECURITY;

-- Política de lectura: cualquier persona puede leer fuentes y ejecuciones
CREATE POLICY "Allow public read access on monitored_sources" ON monitored_sources
  FOR SELECT USING (true);

CREATE POLICY "Allow public read access on agent_runs" ON agent_runs
  FOR SELECT USING (true);
