-- Migración Inicial: Estructura de Tabla de Eventos para Encriptados
-- Ruta: supabase/migrations/schema.sql

-- Crear la tabla de eventos
create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  event_date date not null,
  day_of_week text not null, -- MON, TUE, WED, THU, FRI, SAT, SUN
  time_range text not null,  -- e.g. "18:30 - 22:00"
  location_type text not null, -- "presencial" o "virtual"
  location_city text not null,  -- "AMBA", "Bogotá", "Santiago"
  location_detail text,      -- e.g. "Espacio Palermo, CABA"
  tags text[] not null,      -- e.g. ["CRIPTO", "FINTECH"]
  luma_url text unique,      -- URL única del evento para evitar duplicados en raspados
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Row Level Security)
alter table events enable row level security;

-- Política de lectura: cualquier persona (público / anon) puede leer eventos
create policy "Allow public read access" on events
  for select using (true);

-- Política de escritura: solo el rol de servicio (service_role) puede modificar
-- Nota: En Supabase, la clave service_role se salta el RLS por defecto. 
-- No creamos políticas de inserción públicas para evitar vulnerabilidades de spam.
